language: java
notifications:
  email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_a6a69c5b1756_key -iv $encrypted_a6a69c5b1756_iv
    -in client-secret.json.enc -out client-secret.json -d
deploy:
  provider: gae
  keyfile: client-secret.json
  project: moltimate
  on:
    all_branches: true
