sudo: required
language: java
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_a6a69c5b1756_key -iv $encrypted_a6a69c5b1756_iv
  -in secrets/secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- mvn -P prod install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn -P prod test -B
deploy:
- provider: gae
  project: moltimate
  keyfile: client-secret.json
  on: master
- provider: gae
  project: moltimate
  version: development
  no_promote: true
  keyfile: client-secret.json
  on: dev
- provider: gae
  skip_cleanup: true
  file: target/moltimate-backend-1.0.0.war
  project: moltimate
  version: deploytest
  no_promote: true
  keyfile: client-secret.json
  on: MOL-10
