# Used by GCP App Engine
runtime: java
env: flex
runtime_config:
    jdk: openjdk8
resources:
    cpu: 2
    memory_gb: 8
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1
readiness_check:
    path: "/healthcheck"
liveness_check:
    path: "/healthcheck"
skip_files:
  - .git/objects/
  - moltimate.mv.db
