## These settings are to be replicated in the aws console.
## Currently they cause issues if ran through ebextensions

option_settings:
  ## Single instance with a min and max of 1
  - namespace: aws:elasticbeanstalk:environment
    option_name: EnvironmentType
    value:  SingleInstance
  - namespace: aws:autoscaling:asg
    option_name: MinSize
    value:  1
  - namespace: aws:autoscaling:asg
    option_name: MaxSize
    value:  1
## Set ec2 instances to use
## This has been commented out because it will
## Enable a load balancer, instance size is
## Manually set in console/save config
  - namespace: aws:ec2:instances
    option_name: InstanceTypes
    value:  t2.small