# This property comes from the activated Maven profile (assigned with `mvn -P profile-name`, defined in pom.xml)
spring:
  profiles:
    active: @activatedSpringProfile@
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.biojava: OFF
