spring:
  cloud:
    gcp:
      project-id: moltimate
      sql:
        database-name: moltimate
        instance-connection-name: moltimate:us-east4:backend-db-sql
  datasource:
    continue-on-error: true
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
