# Used by GCP App Engine
runtime: java
env: flex
runtime_config:
    jdk: openjdk8
service: moltimate-backend
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 5
readiness_check:
    path: "/"
    app_start_timeout_sec: 600
skip_files:
  - .git/objects/
  - target/
  - moltimate.mv.db
